### ISSUE TITLE
posthtml-css-modules - where is difference?

### ISSUE THREAD

**Issue by awinogradov** [posthtml/posthtml-postcss-modules#2]

**Comment by kevinSuttle** [comment]
I think transforming `<style scoped>` tags could be a big deal, as long as the prefix could be specified with the `localIdentName` or something. 

http://css4.rocks/selectors-level-4/scope-pseudo-class.php
https://github.com/vuejs/vue-loader/blob/master/lib/style-rewriter.js#L59
https://vue-loader.vuejs.org/en/features/scoped-css.html
https://github.com/stevenbenisek/posthtml-prefix-class
